#lang racket/base
;;; TEI P5 output.
;;;
;;; TEI already has a vocabulary for physical bibliography, and most projects
;;; never use it. <fw> is "forme work" -- the running titles, signatures and
;;; catchwords that are instructions to the binder rather than to the reader.
;;; <pb/>, <cb/> and <lb/> are the page, column and line of type. <lb break="no"/>
;;; is a word divided across a line. <choice> with <abbr>/<expan> is exactly a
;;; scribal contraction, and with <sic>/<corr> exactly a literal. And <app>
;;; with <rdg wit="..."> is a critical apparatus -- which is what a list of
;;; press variants across copies of one edition actually is.
;;;
;;; TWO DECISIONS WORTH ARGUING WITH.
;;;
;;; *Milestones, not containers.* Verse lines, speeches and typographic lines
;;; cut across one another constantly here: a turned-over verse line is one
;;; verse line across two type lines, and a prose paragraph runs over a page
;;; break. XML cannot nest overlapping hierarchies, and TEI's own answer is
;;; the milestone. So <lb/> is empty and the words are its siblings, and the
;;; verse/prose distinction is carried as an attribute rather than by wrapping
;;; each type line in <l>. The cost is that <l> does not appear; the benefit
;;; is that nothing is misrepresented and the XSLT can group by sibling axis,
;;; which XSLT 1.0 can actually do.
;;;
;;; *Geometry in a foreign namespace.* The whole point of this program is that
;;; the justification is the compositor's, not the browser's, so the computed
;;; position of every word has to survive into the output or the facsimile is
;;; a lie. But an em offset is process data, not text, and has no business
;;; wearing TEI semantics. It goes in the hp: namespace, which is the standard
;;; escape hatch, and a consumer who wants clean TEI can strip one namespace
;;; and lose nothing textual.

(require racket/list racket/string racket/math racket/format
         "metrics.rkt" "compositor.rkt" "book.rkt" "imposition.rkt"
         "press.rkt" "corrector.rkt" "description.rkt")

(provide book->tei HP-NS TEI-NS)

(define TEI-NS "http://www.tei-c.org/ns/1.0")
(define HP-NS "https://handpress.invalid/ns/1.0")

(define (esc s)
  (for/fold ([s (if (string? s) s (format "~a" s))])
            ([p (in-list '(("&" "&amp;") ("<" "&lt;") (">" "&gt;")
                           ("\"" "&quot;")))])
    (string-replace s (car p) (cadr p))))

(define (em x) (real->decimal-string (ems x) 3))

;; ---------------------------------------------------------------------------
;; Header
;; ---------------------------------------------------------------------------

(define (header b run names)
  (define resps
    (for/list ([n (in-list names)])
      (define p (hash-ref PROFILES n #f))
      (format "        <respStmt xml:id=\"comp~a\"><resp>composition</resp><name>Compositor ~a</name>~a</respStmt>"
              (esc n) (esc n)
              (if p (format "<note>~a</note>" (esc (profile-description p))) ""))))
  (define wits
    (if run
        (for/list ([pc (in-list (press-run-copies run))] [i (in-naturals)])
          (format "          <witness xml:id=\"~a\">~a, made up from the heaps</witness>"
                  (copy-id pc) (esc (printed-copy-name pc))))
        '()))
  (string-join
   (append
    (list "  <teiHeader>"
          "    <fileDesc>"
          "      <titleStmt>"
          (format "        <title>~a</title>" (esc (book-title b))))
    resps
    (list "      </titleStmt>"
          "      <publicationStmt>"
          "        <p>Not published. Generated by handpress, a simulation of hand-press composition.</p>"
          "      </publicationStmt>"
          "      <sourceDesc>"
          "        <bibl>"
          (format "          <title>~a</title>" (esc (book-title b)))
          (format "          <extent>~a</extent>" (esc (book-collation b)))
          (format "          <note type=\"measure\">~a ems, ~a column(s), ~a lines to the page</note>"
                  (real->decimal-string (book-format-measure-ems (book-fmt b)) 0)
                  (book-format-columns (book-fmt b))
                  (* (book-format-lines (book-fmt b)) (book-format-columns (book-fmt b))))
          "        </bibl>")
    ;; The Bowers description, in TEI's own vocabulary for physical make-up.
    (list (description-tei-msdesc b run))
    (if (null? wits) '() (cons "        <listWit>" (append wits (list "        </listWit>"))))
    (list "      </sourceDesc>"
          "    </fileDesc>"
          "    <encodingDesc>"
          "      <classDecl>"
          "        <taxonomy xml:id=\"hp.causes\">"
          "          <category xml:id=\"copy\"><catDesc>Follows the copy the compositor received.</catDesc></category>"
          "          <category xml:id=\"habit\"><catDesc>The compositor's own spelling, against his copy.</catDesc></category>"
          "          <category xml:id=\"justification\"><catDesc>Altered so that the line would fill the measure exactly.</catDesc></category>"
          "          <category xml:id=\"misreading\"><catDesc>Misread from the copy: minims, secretary-hand confusions, memory.</catDesc></category>"
          "          <category xml:id=\"foul-case\"><catDesc>A sort taken from an adjoining box of the case.</catDesc></category>"
          "          <category xml:id=\"house-style\"><catDesc>Imposed on the copy by the corrector before setting.</catDesc></category>"
          "        </taxonomy>"
          "      </classDecl>"
          "      <p>Type lines are milestones (<gi>lb</gi>), not containers, because verse lines, speeches and type lines overlap. Word positions are in the hp: namespace: they are process data, not text.</p>"
          "    </encodingDesc>")
    (if (null? (book-preparation b))
        '()
        (list "    <profileDesc>"
              (format "      <correction><p>The corrector made ~a alteration(s) to the copy before it reached the frames. These are house habits, not any workman's, and fall evenly across every stint.</p></correction>"
                      (length (book-preparation b)))
              "    </profileDesc>"))
    (list "  </teiHeader>"))
   "\n"))

(define (copy-id pc)
  (string-downcase (string-replace (printed-copy-name pc) " " "")))

;; ---------------------------------------------------------------------------
;; Body
;; ---------------------------------------------------------------------------

;; (page-sig line word) -> list of (witness-id . reading)
(define (variant-index run)
  (define h (make-hash))
  (when run
    (for ([(name st) (in-hash (press-run-states run))])
      (for ([v (in-list (forme-state-variants st))])
        (define key (list (pvariant-page v) (pvariant-line v) (pvariant-word v)))
        (define corrected-in
          (for/list ([pc (in-list (press-run-copies run))]
                     #:when (hash-ref (printed-copy-states pc) name #f))
            (copy-id pc)))
        (define uncorrected-in
          (for/list ([pc (in-list (press-run-copies run))]
                     #:unless (hash-ref (printed-copy-states pc) name #f))
            (copy-id pc)))
        (hash-set! h key (list (cons uncorrected-in (pvariant-uncorrected v))
                               (cons corrected-in (pvariant-corrected v)))))))
  h)

(define (word->tei w x variants key)
  (define printed (word-printed w))
  (define composed (word-composed w))
  (define just? (for/or ([c (in-list (word-causes w))])
                  (string-prefix? c "justification")))
  (define divided? (for/or ([c (in-list (word-causes w))])
                     (string-prefix? c "second half")))
  (define app (hash-ref variants key #f))
  (define ana
    (cond [app "#foul-case"]
          [(not (string=? printed composed)) "#foul-case"]
          [just? "#justification"]
          [(not (string=? (word-read w) (word-copy w))) "#misreading"]
          [(not (string=? (word-habit w) (word-read w))) "#habit"]
          [else "#copy"]))
  (define inner
    (cond
      ;; A press variant: the readings actually differ between copies, which
      ;; is what an apparatus is for.
      [app
       (string-append
        "<app>"
        (string-join
         (for/list ([r (in-list app)] #:unless (null? (car r)))
           (format "<rdg wit=\"~a\">~a</rdg>"
                   (string-join (for/list ([w (in-list (car r))]) (string-append "#" w)) " ")
                   (esc (cdr r))))
         "")
        "</app>")]
      ;; A literal: what was printed, and what the type should have read.
      [(not (string=? printed composed))
       (format "<choice><sic>~a</sic><corr>~a</corr></choice>" (esc printed) (esc composed))]
      ;; Altered for room. Which way it went matters: a shortened form is an
      ;; abbreviation and takes <abbr>/<expan>, but a *lengthened* one is not
      ;; an abbreviation at all and must not be labelled as one -- calling
      ;; "lorde" an abbreviation of "lord" is simply false, and the rendering
      ;; then tells the reader it was done to save space when it was done to
      ;; fill it. A fuller spelling is an orthographic variant: <orig>/<reg>.
      [(and just? (not (string=? (word-final w) (word-read w)))
            (< (string-length (word-final w)) (string-length (word-read w))))
       (format "<choice><abbr>~a</abbr><expan>~a</expan></choice>"
               (esc printed) (esc (word-read w)))]
      [(and just? (not (string=? (word-final w) (word-read w))))
       (format "<choice><orig>~a</orig><reg>~a</reg></choice>"
               (esc printed) (esc (word-read w)))]
      [else (esc printed)]))
  (format "<w hp:x=\"~a\" hp:w=\"~a\" ana=\"~a\"~a>~a</w>"
          (em x) (em (word-width w)) ana
          (if (word-italic? w) " rend=\"italic\"" "")
          inner))

(define (line->tei l n indent-x variants sig)
  (define spaces (set-line-spaces l))
  (define lb
    (format "<lb n=\"~a\" hp:indent=\"~a\" hp:kind=\"~a\"~a~a/>"
            n (em (set-line-indent l)) (set-line-kind l)
            (if (set-line-turned-over? l) " hp:turned=\"true\"" "")
            ;; A word divided at the end of a line: TEI has an attribute for
            ;; precisely this, and it is almost never used.
            (if (for/or ([w (in-list (set-line-words l))])
                  (for/or ([c (in-list (word-causes w))])
                    (string-prefix? c "word divided")))
                " break=\"no\"" "")))
  (define ws
    (let loop ([ws (set-line-words l)] [i 0] [x (set-line-indent l)] [acc '()])
      (cond
        [(null? ws) (reverse acc)]
        [else
         (loop (cdr ws) (add1 i)
               (+ x (word-width (car ws))
                  (if (< i (length spaces)) (list-ref spaces i) 0))
               (cons (word->tei (car ws) x variants (list sig n i)) acc))])))
  (string-append "        " lb "\n"
                 (if (null? ws) "" (string-append "        " (string-join ws "") "\n"))))

(define (page->tei p fmt variants)
  (define sig (page-sig p))
  (define rt (page-running-title p))
  (define cols
    (let loop ([cs (page-columns p)] [c 1] [n 0] [acc '()])
      (cond
        [(null? cs) (reverse acc)]
        [else
         (define measure
           (if (pair? (car cs))
               (em (set-line-measure (car (car cs))))
               (real->decimal-string (book-format-measure-ems fmt) 3)))
         (define-values (body n*)
           (for/fold ([body '()] [k n] #:result (values (reverse body) k))
                     ([l (in-list (car cs))])
             (values (cons (line->tei l (add1 k) 0 variants sig) body) (add1 k))))
         (loop (cdr cs) (add1 c) n*
               (cons (string-append
                      (format "      <div type=\"column\" n=\"~a\" hp:measure=\"~a\">\n        <cb n=\"~a\"/>\n        <ab>\n"
                              c measure c)
                      (apply string-append body)
                      "        </ab>\n      </div>\n")
                     acc))])))
  (string-append
   (format "    <div type=\"page\" n=\"~a\" resp=\"#comp~a\" hp:forme=\"~a\" hp:pressure=\"~a\">\n"
           (esc sig) (esc (page-compositor p)) (esc (page-forme-name p))
           (real->decimal-string (page-pressure p) 2))
   (format "      <pb n=\"~a\" xml:id=\"pb-~a\"~a/>\n"
           (esc sig) (esc sig)
           (if rt (format " ed=\"~a\"" (esc (running-title-identifier rt))) ""))
   (if rt
       (format "      <fw type=\"head\" place=\"top-centre\" hp:damage=\"~a\">~a</fw>\n"
               (esc (title-fingerprint rt)) (esc (running-title-text rt)))
       "")
   (apply string-append cols)
   (if (string=? (page-signature p) "") ""
       (format "      <fw type=\"sig\" place=\"bot-left\">~a</fw>\n" (esc (page-signature p))))
   (if (string=? (page-catchword p) "") ""
       (format "      <fw type=\"catch\" place=\"bot-right\">~a</fw>\n" (esc (page-catchword p))))
   "    </div>\n"))

(define (book->tei b [run #f] [names '("A" "B")])
  (define variants (variant-index run))
  (string-append
   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
   (format "<TEI xmlns=\"~a\" xmlns:hp=\"~a\">\n" TEI-NS HP-NS)
   (header b run names) "\n"
   "  <text>\n    <body>\n"
   (apply string-append
          (for/list ([p (in-list (book-pages b))])
            (page->tei p (book-fmt b) variants)))
   "    </body>\n  </text>\n</TEI>\n"))

(module+ test
  (require rackunit racket/port xml)

  ;; Long enough to fill more than one page, or there is no catchword to find.
  (define b (set-book (make-house #:fmt QUARTO #:seed 1623)
                      (apply string-append
                             (for/list ([i (in-range 14)])
                               (string-append
                                "King. And can you by no drift of conference\n"
                                "Get from him why he puts on this confusion,\n"
                                "Grating so harshly all his days of quiet\n"
                                "With turbulent and dangerous lunacy?\n\n")))))
  (define r (run-press b #:copies 3 #:seed 1623 #:proof-rate 1.0))
  (define x (book->tei b r))

  ;; Well-formed, and parseable by a real XML reader.
  (check-not-exn (lambda () (read-xml (open-input-string x))))
  (check-true (regexp-match? #px"<TEI xmlns=\"http://www.tei-c.org/ns/1.0\"" x))
  (check-true (regexp-match? #px"xmlns:hp=" x))

  ;; The vocabulary that matters is actually used.
  (check-true (regexp-match? #px"<fw type=\"sig\"" x) "signatures are forme work")
  (check-true (regexp-match? #px"<fw type=\"catch\"" x) "so are catchwords")
  (check-true (regexp-match? #px"<lb n=" x) "type lines are milestones")
  (check-true (regexp-match? #px"<respStmt" x) "compositors are responsible parties")
  (check-true (regexp-match? #px"<taxonomy" x) "causes are a declared taxonomy")
  (check-true (regexp-match? #px"ana=\"#" x) "and every word points into it")

  ;; Escaping is already proved by read-xml above: an unescaped & from the
  ;; text (the compositor sets a great many ampersands) would fail the parse.

  ;; Word count in the TEI matches the type.
  (define in-type
    (for*/sum ([p (in-list (book-pages b))] [l (in-list (page-all-lines p))])
      (length (set-line-words l))))
  (check-equal? (length (regexp-match* #px"<w " x)) in-type))
