"""Which words a printed book capitalises mid-sentence, and how often.

The compositor's capitals are a habit as his spelling is -- Blayney identifies
Okes's B by "capitalised King" -- and the program had no mechanism for any of
it. This writes the table the mechanism selects from, so that the rule can
CHOOSE among the words the period actually capitalised and cannot invent one.
Exactly the discipline lexicon.rkt imposes on spelling.

Only mid-sentence occurrences are counted. A word at the head of a sentence is
capitalised by rule and says nothing about anybody's habit.

A word capitalised nearly always is a proper name -- `london', `christ' -- and
carries no choice, so those are dropped. What is left is the variable practice:
`king' at 77%, `church' at 88%, `faith' at 24%, `loue' at 11%.

    python tools/build-capitals.py [sample size] > lexicon/capitals-1580-1640.rktd
"""
import glob, re, sys, io, random, collections, statistics

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

files = sorted(glob.glob(r"corpus/texts/*.headed.xml"))
random.seed(1607)
n_sample = int(sys.argv[1]) if len(sys.argv) > 1 else 600
sample = random.sample(files, min(n_sample, len(files)))

WORD = re.compile(r"[A-Za-zſ][A-Za-zſ']*")
OPENER = re.compile(r"[.?!]\s*$")

cap = collections.Counter()
low = collections.Counter()
docs = 0

for f in sample:
    raw = open(f, encoding="utf-8", errors="replace").read()
    head = raw[: raw.find("<EEBO>") if "<EEBO>" in raw else 3000]
    if not re.search(r"<LANGUAGE>eng</LANGUAGE>", head):
        continue
    m = re.search(r"<DATE>[^<]*?(1[56]\d\d)", head)
    if not m or not (1580 <= int(m.group(1)) <= 1640):
        continue
    i = raw.find("<EEBO>")
    body = re.sub(r"<[^>]*>", " ", raw[i:] if i > 0 else raw)
    words = body.split()
    if len(words) < 2000:
        continue
    docs += 1
    prev_ends = True
    for tok in words:
        w = WORD.search(tok)
        if w:
            if not prev_ends:
                bare = w.group(0).replace("ſ", "s")
                (cap if bare[0].isupper() else low)[bare.lower()] += 1
        prev_ends = bool(OPENER.search(tok))

MIN_OCCURRENCES = 150
LOWEST = 0.04      # below this the capital is a slip, not a practice
HIGHEST = 0.90     # above it the word is a name and carries no choice

rows = []
for w, c in cap.items():
    total = c + low.get(w, 0)
    if total < MIN_OCCURRENCES or not w.isalpha():
        continue
    share = c / total
    if LOWEST <= share <= HIGHEST:
        rows.append((w, share, total))
rows.sort()

shares = [s for _, s, _ in rows]
print(";; Generated by tools/build-capitals.py -- do not edit.")
print(f";; {docs} English books of 1580-1640, 2,000 words or more.")
print(f";; {len(rows)} word-types capitalised mid-sentence between "
      f"{int(100*LOWEST)}% and {int(100*HIGHEST)}% of the time,")
print(f";; on at least {MIN_OCCURRENCES} mid-sentence occurrences. "
      f"Median share {statistics.median(shares):.3f}.")
print(";;")
print(";; A word capitalised more often than that is a proper name and is left")
print(";; out: it carries no choice. One capitalised less often is a slip.")
print("(")
for w, share, total in rows:
    print(f' ("{w}" {share:.3f} {total})')
print(")")
