"""Extract Mulcaster's General Table from the EEBO-TCP text of the Elementarie.

    python tools/mulcaster.py path/to/elementary.xml -o mulcaster.rktd

Richard Mulcaster, `The first part of the elementarie which entreateth chieflie
of the right writing of our English tung' (London, 1582), closes with an
alphabetical table of English words in the spellings he recommends -- the first
serious attempt at an English orthographic standard, and the earliest statement
of the rule that a terminal E lengthens the preceding vowel (mad / made).

Why this is wanted here
-----------------------
The attestation lexicon says which spellings the trade actually used. It cannot
say which of them the period thought correct, and it says nothing at all about
a word that never turns up in the corpus. Mulcaster supplies both: a recommended
form for some eight thousand words, and -- because his table is a standard
rather than a record -- a way of telling a normalising change from a merely
variant one.

The two sources answer different questions, and the program needs both:

    corpus     what compositors set        (frequency)
    Mulcaster  what was held to be right   (authority)

The table is his own; the words are ordinary English. Nothing is reproduced
here but the word list, which is what a dictionary is.
"""

import argparse
import re
import sys

# The table is the run of <div type="section"> blocks near the end whose head
# is a single letter, each holding a <list> of <item> words.
#
# Six letters -- E, G, H, I, J, U -- put one or more <note>s between the head
# and the list, where Mulcaster remarks on the letter itself: that H is "so
# gentlie pronounced, or rather so not pronounced in our tung", that the strong
# G before E and I is warranted by the Greek, that the first person is always
# capital. Those notes are the rules the table illustrates, so they are kept
# rather than skipped, and the letters they belong to are no longer lost.
SECTION = re.compile(
    r'<div type="section">\s*<head>([A-Z])</head>(.*?)<list>(.*?)</list>',
    re.S)
ITEM = re.compile(r"<item>(.*?)</item>", re.S)
NOTE = re.compile(r"<note>(.*?)</note>", re.S)
TAG = re.compile(r"<[^>]+>")

WORD = re.compile(r"^[a-zA-Zſ]+$")


def clean(s):
    s = TAG.sub("", s)
    s = s.replace("ſ", "s").replace("&amp;", "&")
    s = s.strip().strip(".,;:").strip()
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("xml")
    ap.add_argument("-o", "--out", default="mulcaster.rktd")
    args = ap.parse_args()

    src = open(args.xml, encoding="utf-8", errors="replace").read()

    words = []
    seen = set()
    letters = []
    notes = []
    for letter, between, body in SECTION.findall(src):
        for raw in NOTE.findall(between):
            t = " ".join(clean(raw).split())
            if t:
                notes.append((letter, t))
        n = 0
        for raw in ITEM.findall(body):
            w = clean(raw)
            if not w or not WORD.match(w):
                continue
            lw = w.lower()
            if lw in seen:
                continue
            seen.add(lw)
            words.append(lw)
            n += 1
        if n:
            letters.append("%s:%d" % (letter, n))

    if not words:
        print("no table found -- is this the Elementarie?", file=sys.stderr)
        return 1

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(";; Generated by tools/mulcaster.py -- do not edit.\n")
        f.write(";; Richard Mulcaster, The first part of the elementarie\n")
        f.write(";; (London, 1582), the General Table: %d words.\n" % len(words))
        f.write(";; %s\n" % " ".join(letters))
        f.write("((words\n  ")
        for w in sorted(words):
            f.write('"%s" ' % w)
        f.write(")\n (notes\n")
        for letter, t in notes:
            f.write('  ("%s" . %s)\n' % (letter, repr(t).replace("'", '"', 2)
                                         if False else '"%s"' % t.replace('"', "'")))
        f.write(" ))\n")

    print("%d words from Mulcaster's table -> %s" % (len(words), args.out))
    print("   " + " ".join(letters))
    print("   %d notes on particular letters" % len(notes))
    return 0


if __name__ == "__main__":
    sys.exit(main())
